### PR TITLE
feat:heading added

### LINKED ISSUE #7: Reloading Issues in netlify and padding of button

### PR DESCRIPTION
**Pull request by prajwalzingare**
build a wishlist page heading

### CODE REVIEW

**Review by chhakuli123 — COMMENTED** [review]
LGTM

**Review by chhakuli123 — APPROVED** [review]
ready to merge

**Review by chhakuli123 — CHANGES_REQUESTED** [review]
add some styling

**Comment by prajwalzingare** [comment]
ohk i will do that

**Review by prajwalzingare — COMMENTED** [review]
ohk

**Review by chhakuli123 — COMMENTED** [review]
LGTM

**Pull request merged**
